title: Journal of Gen AI learning
description: A description of your site..

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

remote_theme: zivong/jekyll-theme-hydure

email: prabu@gatech.edu

cover: /assets/images/camp-lazarus-lighter-overlay.jpeg